pipeline {

    agent any

    stages {

        stage('Clone') {

            steps {

                git 'https://github.com/jmartinezb11-cmd/proyecto-devops-final'

            }

        }

        stage('Build Docker Image') {

            steps {

                sh 'sudo docker build -t proyecto-devops .'

            }

        }

        stage('Deploy Swarm') {

            steps {

                sh 'sudo docker stack deploy -c swarm/docker-stack.yml proyecto'

            }

        }
    }
}
